name: Deploy Node.js project to Azure Linux Function App

on:
  push:

env:
  AZURE_FUNCTIONAPP_NAME: 'budgetease-api'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './backend'
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies and build
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        npm ci
        npm run build --if-present
        npm run test --if-present

    - name: Zip the package
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        zip -r ../functionapp.zip .

    - name: Deploy to Azure Function App using ZIP
      uses: azure/cli@v1
      with:
        inlineScript: |
          echo "${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}" > publishProfile.publishsettings
          az login --only-show-errors --output none --username $(az functionapp deployment list-publishing-profiles --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group budgeteaseapi --xml)
          az functionapp deployment source config-zip \
            --resource-group budgeteaseapi \
            --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
            --src functionapp.zip
