name: Build and Deploy Azure Function (Linux)

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: 'budgetease-api'  # <-- jouw Function App naam
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './backend/dist'
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        npm install

    - name: Zip Function App contents
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        zip -r ../functionapp.zip .

    - name: Deploy to Azure Function App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: functionapp.zip
