name: Build and Deploy Azure Function (Linux)

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: 'budgetease-api'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './backend/dist'
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: |
        cd backend
        npm ci

    - name: Build TypeScript project
      run: |
        cd backend
        npm run build

    - name: Zip Function App files
      run: |
        cd backend/dist
        zip -r functionapp.zip .

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/functionapp.zip'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
